### ISSUE TITLE
Add support for Uniform Distribution

### ISSUE THREAD

**Issue by hot9cups** [hot9cups/probdists#14]
Go through the [Gaussian](https://github.com/hot9cups/probdists/blob/main/probdists/Gaussiandistribution.py) distribution class, the [Binomial](https://github.com/hot9cups/probdists/blob/main/probdists/Binomialdistribution.py) class and the [Exponential](https://github.com/hot9cups/probdists/blob/main/probdists/Exponentialdistribution.py) class which are subclasses of [General](https://github.com/hot9cups/probdists/blob/main/probdists/Generaldistribution.py) distribution class.

The uniform distribution is the simplest probability distribution.
I would like to expand this to include the Uniform Probability Distribution.
It should be able to calculate mean, standard deviation, and create basic plots like those in the classes I linked.

**Comment by fibonacci-spirals** [comment]
Hi @hot9cups I would like to work on this!

**Comment by hot9cups** [comment]
@fibonacci-spirals Hope you're doing well. How are you progressing with the issue? :)

**Comment by fibonacci-spirals** [comment]
@hot9cups Raised a PR [here](https://github.com/hot9cups/probdists/pull/40) Please let me know if there are any changes required.
