### ISSUE TITLE
Add support for Gamma Distribution

### ISSUE THREAD

**Issue by hot9cups** [hot9cups/probdists#15]
Go through the [Gaussian](https://github.com/hot9cups/probdists/blob/main/probdists/Gaussiandistribution.py) distribution class, the [Binomial](https://github.com/hot9cups/probdists/blob/main/probdists/Binomialdistribution.py) class and the [Exponential](https://github.com/hot9cups/probdists/blob/main/probdists/Exponentialdistribution.py) class which are subclasses of [General](https://github.com/hot9cups/probdists/blob/main/probdists/Generaldistribution.py) distribution class.

I would like to expand this to include the Gamma Probability Distribution.
It should be able to calculate mean, standard deviation, and create basic plots like those in the classes I linked.

**Comment by rachitmanas** [comment]
I would like to work on this issue.

**Comment by The-Shwin** [comment]
I opened a PR for to solve this issue since it didn't seem work had already been done.
