### ISSUE TITLE
Create github action to run unittests

### ISSUE THREAD

**Issue by hot9cups** [hot9cups/probdists#2]
Title says it all.

Also, I already have a test.py file, which you can find [here](https://github.com/hot9cups/probdists/blob/main/test.py). So you're free to use that if you want to.
I'd like the github action to run the unittests for every push made to master branch, and for every Pull Request opened.

**Comment by augusto-jm-amaral** [comment]
@hot9cups I will add :D

**Comment by hot9cups** [comment]
Sounds great @augusto-jm-amaral ! Go ahead and create the PR when ready :)

**Comment by Reghill** [comment]
Can I work on it ? Or is it assigned already?

**Comment by hot9cups** [comment]
@Reghill Augusto is working on this already. You can in the meanwhile enhance the unittests, or create some unittests for the exponential distribution that will be added soon. There's also another issue that I opened where needs creation of a github action to check for linting of python code. I look forward to your contributions :)
