### ISSUE TITLE
Add CDF for Binomial Distribution

### ISSUE THREAD

**Issue by hot9cups** [hot9cups/probdists#21]
[Here](https://github.com/hot9cups/probdists/blob/main/probdists/Binomialdistribution.py) is the Binomial distribution class.

It contains the PDF function but currently does not have a CDF function.
I would like it contain the CDF too.

I would also like appropriate unittests to be included in the [test.py file](https://github.com/hot9cups/probdists/blob/main/test.py)

**Comment by zer0link** [comment]
Hi I like to be assigned to this issue

**Comment by hot9cups** [comment]
@zer0link Great! Good luck!
