### ISSUE TITLE
Add CDF for Gaussian Distribution

### ISSUE THREAD

**Issue by hot9cups** [hot9cups/probdists#22]
[Here](https://github.com/hot9cups/probdists/blob/main/probdists/Gaussiandistribution.py) is the Gaussian distribution class.

It contains the PDF function but currently does not have a CDF function.
I would like it contain the CDF too.

I would also like appropriate unittests to be included in the [test.py file](https://github.com/hot9cups/probdists/blob/main/test.py)

**Comment by RimorRes** [comment]
Hi, can I work on this?

**Comment by hot9cups** [comment]
Sure thing @RimorRes !
There's just one thing though, I'll need you to start working on this from day after tomorrow, because there are certain issues that I need to sort in the codebase, which I'll be doing tomorrow. Thanks :)

**Comment by RimorRes** [comment]
Ok, so I should start working on this on the 31st of October?

**Comment by hot9cups** [comment]
@RimorRes sure. You can do that, although be sure when you make the PR, you actually refresh the fork to have the latest version of the repo :)

**Comment by RimorRes** [comment]
Sure thing!

**Comment by RimorRes** [comment]
I finished implementing the CDF for the Gaussian distribution and am currently waiting for your go-ahead.
I'm hoping this PR will count towards my Hacktoberfest objective so I'd like to submit as soon as possible if it's fine by you.

**Comment by hot9cups** [comment]
@RimorRes ah, I see.
Right, I understand. In that case, you can open a PR now, and if everything works fine I'll add the hacktoberfest-accepted label immediately. Then I'll get to actually merging it later; that way your PR counts for hacktoberfest while I also get to wait before merging it

**Comment by hot9cups** [comment]
@RimorRes Strike my last message, everything is resolved now, so you can go ahead and create the PR right away :)

**Comment by RimorRes** [comment]
#38
