### ISSUE TITLE
Add CDF for Exponential Distribution

### ISSUE THREAD

**Issue by hot9cups** [hot9cups/probdists#23]
[Here](https://github.com/hot9cups/probdists/blob/main/probdists/Exponentialdistribution.py) is the Exponential distribution class.

It contains the PDF function but currently does not have a CDF function.
I would like it contain the CDF too.

I would also like appropriate unittests to be included in the [test.py file](https://github.com/hot9cups/probdists/blob/main/test.py)

**Comment by basil08** [comment]
@hot9cups may I work on this? 

However, I may be a bit late.

**Comment by hot9cups** [comment]
Alright.

Assigning it to you.
