### ISSUE TITLE
Add CDF for Gamma Distribution

### ISSUE THREAD

**Issue by hot9cups** [hot9cups/probdists#24]
[Here](https://github.com/hot9cups/probdists/blob/main/probdists/Gammadistribution.py) is the Gamma distribution class.

It contains the PDF function but currently does not have a CDF function.
I would like it contain the CDF too.

I would also like appropriate unittests to be included in the [test.py file](https://github.com/hot9cups/probdists/blob/main/test.py)

**Comment by gitrahulgit** [comment]
I would like to work on it!!

**Comment by hot9cups** [comment]
@gitrahulgit Hey !

Just so you know, I see your comment was made a minute before I edited the issue to include the requirement for unittests.
If you're still willing to work on this, let me know and I'll assign it to you :)

**Comment by misterdabu** [comment]
I would like to work on this if you don't mind.

**Comment by hot9cups** [comment]
@misterdabu definitely! I'm assigning it to you, but there's a slight problem that I'm trying to solve at the moment, so you may start working on this from day after tomorrow since I'll be sorting some issues in the codebase tomorrow :)

**Comment by misterdabu** [comment]
Sounds good. I'll hold off for now.

**Comment by hot9cups** [comment]
@misterdabu everything's resolved now, you can go ahead and create a PR :)
