### ISSUE TITLE
Implement Round Function Internally

### ISSUE THREAD

**Issue by mhdzumair** [hot9cups/probdists#25]
It is better to implement the round function internally without calling again and again. I was implement this feature yesterday but today i saw new Gammadistribution. i finished implementation, Unit Test & Usage Docs for other distribution. I will post a PR after finished for gama. What about your idea?

**Comment by hot9cups** [comment]
Hey @mhdzumair 

Do you mean the round function in the unittests?
If that's the case, that does sound like a nice refactoring idea.

And yes, there's also a few other distributions apart from Gamma that are going to be added in the next couple of days.
You could either wait for all of them to be added and implement it in a single go (if that's easier for you), or you're welcome to create a PR for the distributions that are currently available, and you could come back in a couple of days to create another PR for the other distributions :)

**Comment by mhdzumair** [comment]
Ok Sure. I will put PR for now available distribution then you can understand my concept.

**Comment by hot9cups** [comment]
Sounds good :)

**Comment by hot9cups** [comment]
Great, look forward to seeing you again in the future when other distributions get merged!

**Comment by hot9cups** [comment]
@mhdzumair I only noticed now we implemented this for mean and std, but left out the pdf functions. Would you like to take that up as well? If so, please create an issue for it and I'd be glad to assign it to you :)

**Comment by mhdzumair** [comment]
sure bro. ill try it.
