### ISSUE TITLE
Add support for Exponential distribution

### ISSUE THREAD

**Issue by hot9cups** [hot9cups/probdists#3]
Go through the [Gaussian](https://github.com/hot9cups/probdists/blob/main/probdists/Gaussiandistribution.py) distribution class and the [Binomial](https://github.com/hot9cups/probdists/blob/main/probdists/Binomialdistribution.py) class which both are subclasses of [General](https://github.com/hot9cups/probdists/blob/main/probdists/Generaldistribution.py) distribution class.

I would like to expand this to include a third distribution, the Exponential Probability Distribution.
It should be able to calculate mean, standard deviation, and create basic plots like those in the classes I linked.

**Comment by basil08** [comment]
Hey! I am interested. Can I work on this?

**Comment by hot9cups** [comment]
@basil08 sounds great! Before you begin working, could you give me a breakdown of how you plan to go about it ? I'll be glad to assign this issue to you following that! :)

**Comment by basil08** [comment]
@hot9cups I'll be following Gaussian and Binomial classes closely for consistency across the codebase. I plan to implement mean, stdev and plotting pdf of the function.

Though I am not sure how to implement __add__ as the pdf of X1+X2 depends on x. And also, replace_stats_with_data() for this distribution.

**Comment by hot9cups** [comment]
@basil08 Yes, that's exactly how I wanted you to proceed. Yup, that sounds good.

About your other query, I think there are two cases. If the lambda parameter is the same for both distributions, then I think the lambda parameter of the sum of the distributions remains the same? When both the distributions have different parameters, I think it gets a little more tricky, I found one Math Exchange link that tries to address it [here](https://math.stackexchange.com/questions/635443/sum-of-exponential-random-variable-with-different-means)

I suggest you to go ahead and get the basic functionalities that you have in mind coded up, and then we can further discuss the problematic functions after that :)

Good luck !

**Comment by basil08** [comment]
Temporarily commented out `__add__` function. 

Please check.

**Comment by hot9cups** [comment]
@basil08 the PR looks great.
Are you also interested on working on another PR where you create some unittests for your exponential distribution implementation? 

Secondly, would you like to work on the `__add__` magic method in the same PR, or would you require additional time for it and open a separate PR for it, in which case I'll go ahead and merge the current PR?

**Comment by basil08** [comment]
I think another PR for `__add__` would be better.

As for unit tests, I don't know much about GitHub actions but let's see if
I can learn.

**Comment by hot9cups** [comment]
@basil08 alright, another PR is fine as well.

About unit tests, you don't need to know about github actions. I meant adding actual tests in the test.py file for the exponential distribution code. [This](https://github.com/hot9cups/probdists/blob/main/test.py) file.

Someone else's working on actions for it so that's taken care of.

**Comment by basil08** [comment]
Yeah, I am in! 

Thanks.

**Comment by basil08** [comment]
Done. Please check.

**Comment by hot9cups** [comment]
Will close this issue after you're done modifying usage.md :)

**Comment by hot9cups** [comment]
Great work. Appreciate the contribution :)

If you found the repo useful, do consider starring it and sharing it with others who it might be of use to too!
