### ISSUE TITLE
extend round_to args to pdf functn

### ISSUE THREAD

**Issue by mhdzumair** [hot9cups/probdists#32]
I would like to extend the internal round method by adding round_to parameter

**Comment by hot9cups** [comment]
Thank you for your interest @mhdzumair 
I'll be glad to assign this to you! 
There's only one thing, I am going to sort a few issues in the codebase tomorrow, so I request you to start working on this from day after tomorrow. Thanks :)

**Comment by mhdzumair** [comment]
can i rename the pdf() method to calculate_pdf() ? because in some point we can use the pdf value without round so ill introduce new variable in Distribution class as self.pdf than we can assign pdf value to self.pdf withouth round it. although user can calculate pdf value by setting param round_to with calculate_pdf() method. are you ok with it?

**Comment by hot9cups** [comment]
Yes, that sounds like a good idea. Go ahead !
