### ISSUE TITLE
Add support for Triangular distribution

### ISSUE THREAD

**Issue by hot9cups** [hot9cups/probdists#48]
Go through the [Gaussian](https://github.com/hot9cups/probdists/blob/main/probdists/Gaussiandistribution.py) distribution class, the [Binomial](https://github.com/hot9cups/probdists/blob/main/probdists/Binomialdistribution.py) class and the [Exponential](https://github.com/hot9cups/probdists/blob/main/probdists/Exponentialdistribution.py) class which are subclasses of [General](https://github.com/hot9cups/probdists/blob/main/probdists/Generaldistribution.py) distribution class.

I would like to expand this to include another distribution, the Triangular distribution

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Please assign this issue to me, I am new to open source and would like to contribute

**Comment by hot9cups** [comment]
@AmeyaPhadnis-2019H1030012G I never got a response from you, are you still interested in this?

**Comment by CraigP17** [comment]
Hi, can I work on this?

**Comment by hot9cups** [comment]
@CraigP17 I'm gonna wait for a few more hours for Ameya to respond, since I've waited 2 days already. In case they don't respond, I'll be glad to assign this to you. In the meanwhile, could you tell me how you plan to approach this?

**Comment by CraigP17** [comment]
I went through the other distribution classes and testing for each, then review the Triangular distribution and Matplotlib. I'm halfway through the base implementation of it

**Comment by hot9cups** [comment]
Okay I think we've waited enough for Ameya, I'm assigning this to you now, Craig. 

And yep, that sounds good. Make sure to follow the same code style as other classes as far as possible :)

**Comment by CraigP17** [comment]
Will do, thanks!
