### ISSUE TITLE
Create github action for flake8 python linting test 

### ISSUE THREAD

**Issue by hot9cups** [hot9cups/probdists#5]
Add a github action that performs a flake8 python linting test on every push made to master branch as well as every PR opened.

**Comment by augusto-jm-amaral** [comment]
@hot9cups I add flake8 in the same PR of the tests, could the same workflow?

**Comment by hot9cups** [comment]
The same PR is okay if you prefer it that way.

I'm also fine if you want to split it into multiple PRs, either way is fine with me :)
