### ISSUE TITLE
Improve read_data_file() function

### ISSUE THREAD

**Issue by hot9cups** [hot9cups/probdists#8]
Currently the read_data_file() function looks like [this](https://github.com/hot9cups/probdists/blob/9c2670ed2d3156a93ed849457d7ae2974346b708/probdists/Generaldistribution.py#L20)

The limitation of the current code is that it'll only work when the numbers are line separated, ie have one number per line.

This can be improved by letting the user specify the separator, which could be passed as an argument to the function.

**Comment by errpv78** [comment]
Can you assign this issue to me?

**Comment by hot9cups** [comment]
@errpv78 Sure :)
Before you begin, would you mind describing how you plan to go about it?

**Comment by errpv78** [comment]
Thanks and sure I would like to discuss my approach. I am planning to accept the separator as a function parameter and keeping \n as default. And reading the whole file as a string and then splitting on the separator. I'll begin with this approach and will see what modifications I can perform and anything else that is required.

**Comment by hot9cups** [comment]
That sounds great. There's one improvement I can think of in that letting the user input files even in other formats like .csv, .xlsx, etc.

We can take up the details later and you can start drafting your PR now :)

**Comment by errpv78** [comment]
Yeah, sure I'll include that too. Cheers!!

**Comment by hot9cups** [comment]
Great work. Thank you for your contribution :)

**Comment by errpv78** [comment]
You're welcome and had a good experience working on that. Cheers!!

**Comment by hot9cups** [comment]
@errpv78 :) I Look forward to working with you in the future! If you'd like to connect, you can reach out to me on discord `hot9cups#3125` and we can discuss something cool to work on ! Cheers mate!

**Comment by errpv78** [comment]
Yeah sure
